# - name: Create Config file
#   ansible.builtin.template:
#     src: s-jobb.xml
#     dest: /tmp/s-jobb.xml

# - name: Create Job
#   community.general.jenkins_job:
#     config: "{{ lookup('file', '/tmp/s-jobb.xml') }}"
#     name: "{{item.dir}}/{{item.name}}"
#     url: http://172.31.9.181:8080
#     user: admin
#     password: "{{jenkins_password}}"

- name: Create Config file
  ansible.builtin.template:
    src: m-jobb.xml
    dest: /tmp/m-jobb.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-jobb.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url:http://172.31.9.181:8080
    user: admin
    password: "{{jenkins_password}}"
